// Operator feedback for server actions. In production Next.js hides the message of an Error thrown by a server action, so the operator would only
// see a generic failure. Actions therefore REDIRECT back with a short code (?f=erro:<code> | ?f=ok:<code>) and the shell shows the text below.
// Only codes from this whitelist are ever rendered: arbitrary text in the URL can never reach the screen.
export const FEEDBACK = {
  // success
  'ok:lead_registrado': 'Lead registrado.',
  'ok:proposta_ja_existia': 'Esta proposta já existia (mesmo banco e ADE). Nada foi duplicado.',
  'ok:esteira_movida': 'Etapa atualizada.',
  'ok:lead_assumido': 'Lead agora é seu.',
  'ok:meta_salva': 'Meta salva.',
  'ok:etapa_salva': 'Etapa salva.',
  'ok:isencao_salva': 'Isenção de imposto atualizada.',
  'ok:comissao_calculada': 'Comissão calculada e congelada nesta proposta.',
  'ok:distribuicao_salva': 'Distribuição de leads salva.',
  'ok:cliente_reconhecido': 'Este CPF já era cliente da empresa. Nada foi duplicado: os contatos novos entraram no histórico.',
  'ok:cliente_de_outro': 'Este CPF já é cliente da empresa e está com outra pessoa da equipe. Os contatos novos foram registrados; fale com seu supervisor para assumir o atendimento.',
  'ok:lead_atualizado': 'Lead atualizado.',
  'ok:lead_convertido': 'Lead convertido em cliente. Você já pode fazer uma simulação.',
  'ok:cliente_cadastrado': 'Cliente cadastrado.',
  'ok:simulacao_registrada': 'Simulação registrada. Agora você pode criar a proposta.',
  'ok:proposta_criada': 'Proposta registrada na esteira.',
  'ok:doc_enviado': 'Documento enviado.',
  'ok:checklist_preparado': 'Checklist de documentos preparado.',
  'ok:doc_vinculado': 'Documento vinculado à proposta.',
  'ok:requisito_validado': 'Documento validado.',
  'ok:enviado_digitacao': 'Proposta enviada para a operação.',
  'ok:rota_criada': 'Rota comercial criada.',
  'ok:tabela_criada': 'Tabela criada. Agora crie uma versão com taxa/coeficiente e publique.',
  'ok:versao_criada': 'Versão criada como rascunho. Publique para liberar simulações.',
  'ok:versao_publicada': 'Versão publicada. Já pode ser usada em simulações.',
  'ok:checklist_criado': 'Checklist criado como rascunho. Adicione os documentos e publique.',
  'ok:item_adicionado': 'Documento adicionado ao checklist.',
  'ok:checklist_publicado': 'Checklist publicado.',
  'ok:etapas_criadas': 'Etapas padrão da operação criadas.',
  'ok:banco_cadastrado': 'Banco cadastrado.',
  'ok:provedor_cadastrado': 'Provedor cadastrado.',
  'ok:convenio_habilitado': 'Convênio habilitado para a sua organização.',
  'ok:convenio_cadastrado': 'Convênio cadastrado.',
  'ok:grupo_cadastrado': 'Grupo de comissão cadastrado.',
  'ok:situacao_atualizada': 'Situação atualizada.',
  'ok:condicao_salva': 'Condição comercial salva com todos os grupos de comissão.',
  'ok:endereco_salvo': 'Endereço salvo.',
  'ok:cliente_endereco_pendente': 'Cliente cadastrado, mas o endereço não foi salvo. Abra o cliente e salve o endereço.',
  'ok:atencao_atualizada': 'Alerta atualizado.',
  'ok:condicoes_importadas': 'Condições importadas.',
  'ok:politica_salva': 'Política de repasse salva como nova versão. Ela vale para as próximas condições; o que já foi cadastrado não muda.',
  'ok:previa_validada': 'Arquivo válido. Nada foi gravado ainda: confira o resumo e envie de novo escolhendo Importar.',
  'ok:grupo_vendedor_cadastrado': 'Grupo de Vendedor cadastrado.',
  'ok:vendedor_cadastrado': 'Vendedor cadastrado.',
  'ok:vendedor_atualizado': 'Cadastro do vendedor atualizado.',
  'ok:sub_regra_publicada': 'Nova regra SUB publicada. O histórico anterior foi preservado.',
  'ok:fator_perfil_cadastrado': 'Perfil de fator cadastrado.',
  'ok:fator_publicado': 'Fator publicado.',
  'ok:fatores_importados': 'Fatores importados e publicados.',
  'ok:tipo_contrato_cadastrado': 'Tipo de Contrato cadastrado.',
  'ok:tipo_contrato_atualizado': 'Configuração do Tipo de Contrato atualizada.',
  'ok:regra_comissao_salva': 'Regra de comissão salva como nova versão.',
  // errors
  'erro:nome_invalido': 'Informe um nome válido.',
  'erro:valor_invalido': 'Valor inválido. Use o formato 9.500,00 e informe ao menos o valor solicitado ou o liberado.',
  'erro:prazo_invalido': 'Prazo inválido: informe de 1 a 420 meses.',
  'erro:ade_obrigatorio': 'Proposta já digitada precisa do número no banco (ADE).',
  'erro:ade_invalido': 'ADE inválido: use letras, números, ponto, barra ou hífen.',
  'erro:nota_obrigatoria': 'Escreva uma observação (onde viu, o que falta).',
  'erro:prazo_pendencia': 'Informe até quando a pendência precisa ser resolvida.',
  'erro:movimento_invalido': 'Esta proposta não pode ir para essa etapa a partir da etapa atual.',
  'erro:lead_ja_assumido': 'Outra pessoa já assumiu este lead.',
  'erro:ultima_etapa': 'Esta é a única etapa ativa deste tipo. Ative outra do mesmo tipo antes de desligar esta.',
  'erro:etapa_em_uso': 'Há propostas nesta etapa. Mova-as antes de desligar.',
  'erro:percentual_invalido': 'Percentual inválido: use de 0 a 100, com até 4 casas (ex.: 6 ou 6,5).',
  'erro:rateio_acima_100': 'Gerente + supervisor + vendedor não pode passar de 100% no modo cascata.',
  'erro:comissao_sem_regra': 'Configure a regra de comissão da empresa (Configurações > Comissão) antes de calcular.',
  'erro:comissao_sem_condicao': 'Esta tabela não tem condição de comissão para o prazo e valor da proposta.',
  'erro:comissao_ambigua': 'Há mais de uma condição possível para esta proposta. Escolha a condição.',
  'erro:comissao_congelada': 'A proposta já foi paga: a comissão está congelada.',
  'erro:comissao_excede': 'Os percentuais configurados pagam mais do que a empresa recebe. Revise as regras.',
  'erro:canal_invalido': 'Canal inválido.',
  'erro:cpf_invalido': 'CPF inválido. Confira os 11 dígitos.',
  'erro:cpf_duplicado': 'Já existe um cliente com este CPF nesta organização.',
  'erro:email_invalido': 'E-mail inválido.',
  'erro:requisicao_invalida': 'Não foi possível entender o pedido. Atualize a página e tente de novo.',
  'erro:motivo_obrigatorio': 'Informe o motivo da perda.',
  'erro:sem_permissao': 'Seu perfil não pode fazer isto.',
  'erro:indisponivel': 'Este recurso ainda não está disponível neste ambiente.',
  'erro:inesperado': 'Não foi possível concluir. Nada foi alterado; tente de novo. Se repetir, avise o supervisor.',
  'erro:proposta_duplicada': 'Esta simulação já virou proposta.',
  'erro:simulacao_indisponivel': 'Esta simulação não está mais disponível para proposta.',
  'erro:doc_invalido': 'Escolha o cliente, o tipo de documento e o arquivo.',
  'erro:doc_vazio': 'O arquivo está vazio.',
  'erro:doc_grande': 'O arquivo passa de 4 MB. Reduza ou comprima o arquivo (foto menor / PDF menor) e envie de novo.',
  'erro:doc_formato': 'Formato não permitido. Envie PDF, JPG, PNG ou WebP.',
  'erro:doc_duplicado': 'Este mesmo arquivo já foi enviado para este cliente.',
  'erro:doc_indisponivel': 'Cliente ou tipo de documento indisponível.',
  'erro:doc_armazenamento': 'Não foi possível guardar o arquivo. Tente de novo.',
  'erro:doc_registro': 'O arquivo foi guardado, mas o registro falhou. Não envie de novo: avise o supervisor.',
  'erro:doc_incompativel': 'Este documento não corresponde ao tipo exigido.',
  'erro:checklist': 'Não foi possível preparar o checklist. Confirme que existe um checklist publicado para este produto.',
  'erro:envio_digitacao': 'A proposta não pôde ser enviada. Confirme que os documentos obrigatórios estão anexados e validados.',
  'erro:requisito': 'Não foi possível atualizar o documento.',
  'erro:sim_customer_not_found_or_forbidden': 'Cliente não encontrado nesta organização.',
  'erro:sim_published_table_version_not_available': 'A tabela escolhida não está publicada para esta organização.',
  'erro:sim_term_below_table_minimum': 'Prazo abaixo do mínimo da tabela.',
  'erro:sim_term_above_table_maximum': 'Prazo acima do máximo da tabela.',
  'erro:sim_invalid_amount': 'Informe um valor solicitado válido.',
  'erro:sim_invalid_term': 'Informe um prazo válido.',
  'erro:sim_condition_not_found': 'Não há condição cadastrada para este Tipo de Contrato e prazo nesta tabela.',
  'erro:duplicado': 'Já existe um registro com este código ou combinação.',
  'erro:catalogo_invalido': 'Confira os campos: valores numéricos, prazos e seleções.',
  'erro:cat_rate_or_coefficient_required': 'Informe pelo menos a taxa ou o coeficiente antes de publicar.',
  'erro:cat_version_not_draft': 'Esta versão já foi publicada e não pode mais mudar.',
  'erro:cat_template_has_no_items': 'Adicione pelo menos um documento ao checklist antes de publicar.',
  'erro:cat_template_not_draft': 'Este checklist já foi publicado e não pode mais mudar.',
  'erro:cat_sem_referencia': 'O catálogo de referência (bancos, produtos, tipos de documento) ainda não foi carregado pelo administrador da plataforma.',
  'erro:com_condition_already_exists': 'Já existe uma condição com este Tipo de Contrato e prazo nesta versão.',
  'erro:com_invalid_shares': 'Percentual de grupo inválido. Use de 0 a 100.',
  'erro:com_duplicate_group_share': 'O mesmo grupo foi informado duas vezes.',
  'erro:com_commission_group_not_found': 'Grupo de comissão não encontrado ou inativo.',
  'erro:com_production_shares_exceed_received_commission': 'Um grupo não pode receber mais do que a comissão recebida pela empresa.',
  'erro:com_policy_not_found': 'Política de repasse não encontrada ou inativa.',
  'erro:com_policy_group_inactive': 'Um grupo da política de repasse está inativo. Reative o grupo ou salve uma nova versão da política.',
  'erro:com_policy_group_must_use_received_basis': 'A política de repasse só aceita grupos calculados sobre a comissão recebida.',
  'erro:com_invalid_policy': 'Confira a política: nome, base (bruta ou líquida), desconto e percentuais de 0 a 100.',
  'erro:com_policy_already_exists': 'Já existe uma política com este nome.',
  'erro:cep_invalido': 'CEP inválido. Use 8 dígitos.',
  'erro:estado_invalido': 'UF inválida. Use 2 letras.',
  'erro:atencao_nota': 'Para ignorar um alerta, escreva o motivo.',
  'erro:atencao_invalida': 'Não foi possível atualizar o alerta. Atualize a página e tente de novo.',
  'erro:origem_invalida': 'Informe a origem da produção: Própria, ou Terceiro com a empresa de origem.',
  'erro:com_invalid_term': 'Prazo inválido. Use de 1 a 600 meses.',
  'erro:com_coefficient_or_rate_required': 'Informe o coeficiente ou a taxa.',
  'erro:com_invalid_received_commission': 'Informe a comissão recebida (0 a 100).',
  'erro:com_contract_type_not_found': 'Tipo de Contrato não encontrado.',
  'erro:com_condition_not_found': 'Condição não encontrada nesta versão.',
  'erro:com_version_not_draft': 'Esta versão já foi publicada; crie uma nova versão para mudar as condições.',
  'erro:com_national_template_not_available': 'Este convênio nacional não está disponível.',
  'erro:com_sem_grupos': 'Cadastre pelo menos um grupo de comissão antes de registrar condições.',
  'erro:import_invalido': 'O arquivo tem erros e nada foi importado. Corrija e envie de novo.',
  'erro:import_arquivo': 'Envie um arquivo CSV ou XLSX de até 1 MB.',
  'erro:vendedor_invalido': 'Confira nome, categoria, CPF/CNPJ, Grupo de Vendedor e Grupo de Comissão.',
  'erro:sub_regra_invalida': 'Confira o percentual do SUB e a data de vigência.',
  'erro:fator_invalido': 'Confira instituição, escopo, regime, prazo, data e valor do fator.',
  'erro:fator_arquivo': 'Envie um CSV ou XLSX válido de até 2 MB.',
  'erro:fator_colunas': 'Não foi possível identificar Prazo Inicial/Prazo Final/Fator ou há valores inválidos.',
  'erro:regra_comissao_invalida': 'Confira nome, vigência, imposto/desconto, escopo e regras dos grupos.',
} as const
export type FeedbackCode = keyof typeof FEEDBACK
export const isFeedbackCode = (v: unknown): v is FeedbackCode => typeof v === 'string' && Object.prototype.hasOwnProperty.call(FEEDBACK, v)
export const feedbackTone = (c: FeedbackCode) => (c.startsWith('ok:') ? 'ok' : 'erro')

export const feedbackUrl = (path: string, code: FeedbackCode) => `${path}?f=${encodeURIComponent(code)}`

// Maps a database/PostgREST error to a code WITHOUT ever exposing its text.
export function classifyDbFeedback(err: { message?: string; code?: string } | null | undefined): FeedbackCode {
  const m = String(err?.message ?? '')
  if (err?.code === '23505') return 'erro:cpf_duplicado'
  if (/invalid_cpf/.test(m)) return 'erro:cpf_invalido'
  if (/invalid_email/.test(m)) return 'erro:email_invalido'
  if (/full_name_required/.test(m)) return 'erro:nome_invalido'
  if (err?.code === 'PGRST202' || err?.code === '42P01' || err?.code === 'PGRST205') return 'erro:indisponivel'
  if (err?.code === '42501' || /forbidden|not_authorized|permission denied/i.test(m)) return 'erro:sem_permissao'
  return 'erro:inesperado'
}
