import Link from 'next/link'
import { requireAppContext } from '@/lib/appContext'
export default async function ProposalsPage() {
  const { supabase } = await requireAppContext()
  const { data } = await supabase.from('proposals_v2').select('id,status,requested_amount,released_amount,installment_amount,term,created_at,customer_snapshot').order('created_at',{ascending:false}).limit(100)
  return <section><h1 className="text-3xl font-semibold">Propostas</h1><p className="mt-2 text-sm text-slate-400">Snapshots comerciais e evolução das propostas.</p>
    <div className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-800 text-slate-400"><tr><th className="p-4">Cliente</th><th className="p-4">Status</th><th className="p-4">Solicitado</th><th className="p-4">Liberado</th><th className="p-4">Prazo</th></tr></thead><tbody>{data?.map(p=>{const snap=(p.customer_snapshot??{}) as Record<string,unknown>;return <tr key={p.id} className="border-b border-slate-800/60 last:border-0"><td className="p-4"><Link href={`/app/propostas/${p.id}`} className="font-medium hover:text-emerald-400">{String(snap.full_name??snap.name??'Cliente')}</Link></td><td className="p-4"><span className="rounded-full bg-slate-800 px-2.5 py-1 text-xs">{p.status}</span></td><td className="p-4">{p.requested_amount?Number(p.requested_amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}</td><td className="p-4">{p.released_amount?Number(p.released_amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}</td><td className="p-4">{p.term??'—'}</td></tr>})}{!data?.length&&<tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhuma proposta criada.</td></tr>}</tbody></table></div></div>
  </section>
}
