-- PREPARED, NOT APPLIED. Commercial Model V3 (docs/CORBAN-COMMERCIAL-MODEL-V3.md), foundation. Forward-only, additive, compatible with history.
-- No SECURITY DEFINER. No rename, no drop, no data rewritten. Legacy global tables (banks, providers, agreements, products, modalities) stay and keep working;
-- V3 adds tenant-owned layers next to them and relaxes (never removes) what a V3 route does not need.
--
-- Layers
--   1. Platform structure (global, read-only for tenants): contract_types (independent of any product) and national_agreement_templates (27 state governments /
--      Distrito Federal + 26 capital city halls; NOT tied to a bank; NOT active for anyone until a tenant enables them).
--   2. Tenant-owned catalog: organization_banks, organization_providers, organization_agreements (custom or enabled from a template), commission_groups (dynamic).
--   3. Routes: organization_product_routes gains org_bank_id / org_provider_id / org_agreement_id and its legacy columns become nullable; a CHECK allows exactly one
--      of the two shapes (all-legacy or V3). Tables, versions, checklists, proposals keep hanging on the route: nothing downstream changes.
--   4. Commercial conditions (per DRAFT table version; immutable once the version is published): contract type + term + coefficient/rate (readable by every member,
--      the simulation needs them) and, separately and supervisor+ only, the received commission and ONE share per commission group, all written in ONE call
--      (save_commercial_condition). Money/percentages are NUMERIC, never float.
--   3b. Payout policies (repasse por grupo): tenant-owned, immutable versions, % of the commission RECEIVED per group, gross or net base; applied to conditions by the RPC.
--       Groups are ALTERNATIVE sellers (Corretor OR Parceiro...), so caps are per group, never a sum. Route also carries Origem da Produção (own / third_party).
--   5. create_simulation_for_condition: governed simulation that takes coefficient/rate from the condition (commission is never copied).
-- Technical identifiers: every new tenant row gets an opaque tech_key generated by the database; users never type or see it.

-- ---------------------------------------------------------------- 1. platform structure
create table public.contract_types(
 id uuid primary key default gen_random_uuid(),
 tech_key text not null unique,
 name text not null check (length(btrim(name)) between 1 and 80),
 sort_order integer not null default 0,
 is_active boolean not null default true,
 created_at timestamptz not null default now()
);
create unique index contract_types_name_key on public.contract_types(lower(btrim(name)));
insert into public.contract_types(tech_key,name,sort_order) values
 ('novo','Novo',10),('refinanciamento','Refinanciamento',20),('compra_de_divida','Compra de Dívida',30),('portabilidade','Portabilidade',40)
on conflict (tech_key) do nothing;

create table public.national_agreement_templates(
 id uuid primary key default gen_random_uuid(),
 tech_key text not null unique,
 kind text not null check (kind in ('state_government','capital_city_hall')),
 name text not null unique check (length(btrim(name)) between 1 and 120),
 uf char(2) not null,
 city text,
 sort_order integer not null default 0,
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 check ((kind='capital_city_hall' and city is not null) or (kind='state_government' and city is null))
);
-- 26 states + Distrito Federal (Brasília is not a municipality: the DF has a Governo, not a Prefeitura)
insert into public.national_agreement_templates(tech_key,kind,name,uf,sort_order) values
 ('gov-ac','state_government','Governo do Acre','AC',1),('gov-al','state_government','Governo de Alagoas','AL',2),('gov-ap','state_government','Governo do Amapá','AP',3),
 ('gov-am','state_government','Governo do Amazonas','AM',4),('gov-ba','state_government','Governo da Bahia','BA',5),('gov-ce','state_government','Governo do Ceará','CE',6),
 ('gov-df','state_government','Governo do Distrito Federal','DF',7),('gov-es','state_government','Governo do Espírito Santo','ES',8),('gov-go','state_government','Governo de Goiás','GO',9),
 ('gov-ma','state_government','Governo do Maranhão','MA',10),('gov-mt','state_government','Governo de Mato Grosso','MT',11),('gov-ms','state_government','Governo de Mato Grosso do Sul','MS',12),
 ('gov-mg','state_government','Governo de Minas Gerais','MG',13),('gov-pa','state_government','Governo do Pará','PA',14),('gov-pb','state_government','Governo da Paraíba','PB',15),
 ('gov-pr','state_government','Governo do Paraná','PR',16),('gov-pe','state_government','Governo de Pernambuco','PE',17),('gov-pi','state_government','Governo do Piauí','PI',18),
 ('gov-rj','state_government','Governo do Rio de Janeiro','RJ',19),('gov-rn','state_government','Governo do Rio Grande do Norte','RN',20),('gov-rs','state_government','Governo do Rio Grande do Sul','RS',21),
 ('gov-ro','state_government','Governo de Rondônia','RO',22),('gov-rr','state_government','Governo de Roraima','RR',23),('gov-sc','state_government','Governo de Santa Catarina','SC',24),
 ('gov-sp','state_government','Governo de São Paulo','SP',25),('gov-se','state_government','Governo de Sergipe','SE',26),('gov-to','state_government','Governo do Tocantins','TO',27)
on conflict (tech_key) do nothing;
insert into public.national_agreement_templates(tech_key,kind,name,uf,city,sort_order) values
 ('pref-rio-branco','capital_city_hall','Prefeitura de Rio Branco','AC','Rio Branco',101),('pref-maceio','capital_city_hall','Prefeitura de Maceió','AL','Maceió',102),
 ('pref-macapa','capital_city_hall','Prefeitura de Macapá','AP','Macapá',103),('pref-manaus','capital_city_hall','Prefeitura de Manaus','AM','Manaus',104),
 ('pref-salvador','capital_city_hall','Prefeitura de Salvador','BA','Salvador',105),('pref-fortaleza','capital_city_hall','Prefeitura de Fortaleza','CE','Fortaleza',106),
 ('pref-vitoria','capital_city_hall','Prefeitura de Vitória','ES','Vitória',107),('pref-goiania','capital_city_hall','Prefeitura de Goiânia','GO','Goiânia',108),
 ('pref-sao-luis','capital_city_hall','Prefeitura de São Luís','MA','São Luís',109),('pref-cuiaba','capital_city_hall','Prefeitura de Cuiabá','MT','Cuiabá',110),
 ('pref-campo-grande','capital_city_hall','Prefeitura de Campo Grande','MS','Campo Grande',111),('pref-belo-horizonte','capital_city_hall','Prefeitura de Belo Horizonte','MG','Belo Horizonte',112),
 ('pref-belem','capital_city_hall','Prefeitura de Belém','PA','Belém',113),('pref-joao-pessoa','capital_city_hall','Prefeitura de João Pessoa','PB','João Pessoa',114),
 ('pref-curitiba','capital_city_hall','Prefeitura de Curitiba','PR','Curitiba',115),('pref-recife','capital_city_hall','Prefeitura do Recife','PE','Recife',116),
 ('pref-teresina','capital_city_hall','Prefeitura de Teresina','PI','Teresina',117),('pref-rio-de-janeiro','capital_city_hall','Prefeitura do Rio de Janeiro','RJ','Rio de Janeiro',118),
 ('pref-natal','capital_city_hall','Prefeitura de Natal','RN','Natal',119),('pref-porto-alegre','capital_city_hall','Prefeitura de Porto Alegre','RS','Porto Alegre',120),
 ('pref-porto-velho','capital_city_hall','Prefeitura de Porto Velho','RO','Porto Velho',121),('pref-boa-vista','capital_city_hall','Prefeitura de Boa Vista','RR','Boa Vista',122),
 ('pref-florianopolis','capital_city_hall','Prefeitura de Florianópolis','SC','Florianópolis',123),('pref-sao-paulo','capital_city_hall','Prefeitura de São Paulo','SP','São Paulo',124),
 ('pref-aracaju','capital_city_hall','Prefeitura de Aracaju','SE','Aracaju',125),('pref-palmas','capital_city_hall','Prefeitura de Palmas','TO','Palmas',126)
on conflict (tech_key) do nothing;

alter table public.contract_types enable row level security;
alter table public.national_agreement_templates enable row level security;
revoke all on public.contract_types,public.national_agreement_templates from public,anon,authenticated;
grant select on public.contract_types,public.national_agreement_templates to authenticated;
create policy contract_types_read on public.contract_types for select to authenticated using (true);
create policy national_agreement_templates_read on public.national_agreement_templates for select to authenticated using (true);

-- ---------------------------------------------------------------- 2. tenant-owned catalog
create table public.organization_banks(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 tech_key text not null default replace(gen_random_uuid()::text,'-',''),
 name text not null check (length(btrim(name)) between 1 and 120),
 official_code text check (official_code is null or length(btrim(official_code)) between 1 and 20),
 is_active boolean not null default true,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (organization_id,id), unique (organization_id,tech_key)
);
create unique index organization_banks_name_key on public.organization_banks(organization_id,lower(btrim(name)));

create table public.organization_providers(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 tech_key text not null default replace(gen_random_uuid()::text,'-',''),
 name text not null check (length(btrim(name)) between 1 and 120),
 provider_type text not null default 'other' check (provider_type in ('bank_direct','master','promotora','correspondent','partner','other')),
 is_active boolean not null default true,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (organization_id,id), unique (organization_id,tech_key)
);
create unique index organization_providers_name_key on public.organization_providers(organization_id,lower(btrim(name)));

create table public.organization_agreements(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 tech_key text not null default replace(gen_random_uuid()::text,'-',''),
 template_id uuid references public.national_agreement_templates(id) on delete restrict,
 name text not null check (length(btrim(name)) between 1 and 120),
 is_active boolean not null default true,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (organization_id,id), unique (organization_id,tech_key)
);
create unique index organization_agreements_name_key on public.organization_agreements(organization_id,lower(btrim(name)));
create unique index organization_agreements_template_key on public.organization_agreements(organization_id,template_id) where template_id is not null;
create index organization_agreements_template_idx on public.organization_agreements(template_id) where template_id is not null;

-- A commission group is a RULE, not a person: it says how the share written in a condition is to be read.
--   percent_of_production          : the percentage is over the production (contract value)
--   percent_of_received_commission : the percentage is over the commission the company received
-- The two are never mixed silently: the condition RPC validates each basis on its own.
create table public.commission_groups(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 tech_key text not null default replace(gen_random_uuid()::text,'-',''),
 name text not null check (length(btrim(name)) between 1 and 80),
 kind text not null default 'other' check (kind in ('broker','partner','referrer','employee','sales_team','counter','supervisor','manager','other')),
 calculation_basis text not null check (calculation_basis in ('percent_of_production','percent_of_received_commission')),
 is_active boolean not null default true,
 sort_order integer not null default 0,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (organization_id,id), unique (organization_id,tech_key)
);
create unique index commission_groups_name_key on public.commission_groups(organization_id,lower(btrim(name)));

create or replace function public.guard_org_catalog_row() returns trigger language plpgsql set search_path='' as $$
begin
 if tg_op='INSERT' then
  if current_user in ('authenticated','anon') then new.created_by:=auth.uid(); end if;
 else
  if new.id is distinct from old.id or new.organization_id is distinct from old.organization_id or new.tech_key is distinct from old.tech_key or new.created_at is distinct from old.created_at then raise exception 'catalog_identity_is_immutable'; end if;
  if (to_jsonb(new)->>'template_id') is distinct from (to_jsonb(old)->>'template_id') then raise exception 'catalog_identity_is_immutable'; end if;
  new.updated_at:=now();
 end if;
 if tg_table_name='organization_agreements' and (to_jsonb(new)->>'template_id') is not null then
  -- an agreement enabled from the national list carries the template's official name (the tenant may not relabel it into something else)
  select t.name into new.name from public.national_agreement_templates t where t.id=new.template_id and t.is_active;
  if new.name is null then raise exception 'national_template_not_available'; end if;
 end if;
 return new;
end $$;
create trigger organization_banks_00_guard before insert or update on public.organization_banks for each row execute function public.guard_org_catalog_row();
create trigger organization_providers_00_guard before insert or update on public.organization_providers for each row execute function public.guard_org_catalog_row();
create trigger organization_agreements_00_guard before insert or update on public.organization_agreements for each row execute function public.guard_org_catalog_row();
create trigger commission_groups_00_guard before insert or update on public.commission_groups for each row execute function public.guard_org_catalog_row();

do $$
declare t text;
begin
 foreach t in array array['organization_banks','organization_providers','organization_agreements','commission_groups'] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('revoke all on public.%I from public,anon,authenticated',t);
  execute format('grant select,insert,update on public.%I to authenticated',t);
  execute format('create policy %I on public.%I for insert to authenticated with check (public.has_active_organization_role(organization_id,array[''admin'',''manager'']))',t||'_insert_manager',t);
  execute format('create policy %I on public.%I for update to authenticated using (public.has_active_organization_role(organization_id,array[''admin'',''manager''])) with check (public.has_active_organization_role(organization_id,array[''admin'',''manager'']))',t||'_update_manager',t);
 end loop;
end $$;
create policy organization_banks_select on public.organization_banks for select to authenticated using (public.is_active_organization_member(organization_id));
create policy organization_providers_select on public.organization_providers for select to authenticated using (public.is_active_organization_member(organization_id));
create policy organization_agreements_select on public.organization_agreements for select to authenticated using (public.is_active_organization_member(organization_id));
-- commission structure is financial: supervisor and above only (fail closed for operators)
create policy commission_groups_select on public.commission_groups for select to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager','supervisor']));

-- ---------------------------------------------------------------- 3. routes: V3 shape next to the legacy one
alter table public.organization_product_routes
 alter column bank_id drop not null, alter column provider_id drop not null, alter column agreement_id drop not null,
 alter column product_id drop not null, alter column modality_id drop not null,
 add column org_bank_id uuid, add column org_provider_id uuid, add column org_agreement_id uuid,
 add column production_origin text check (production_origin in ('own','third_party')),
 add constraint organization_product_routes_org_bank_fk foreign key (organization_id,org_bank_id) references public.organization_banks(organization_id,id) on delete restrict,
 add constraint organization_product_routes_org_provider_fk foreign key (organization_id,org_provider_id) references public.organization_providers(organization_id,id) on delete restrict,
 add constraint organization_product_routes_org_agreement_fk foreign key (organization_id,org_agreement_id) references public.organization_agreements(organization_id,id) on delete restrict,
 add constraint organization_product_routes_shape check (
  (bank_id is not null and provider_id is not null and agreement_id is not null and product_id is not null and modality_id is not null and org_bank_id is null and org_provider_id is null and org_agreement_id is null and production_origin is null)
  or (org_bank_id is not null and org_agreement_id is not null and bank_id is null and provider_id is null and agreement_id is null and product_id is null and modality_id is null
      -- Origem da Produção: Própria (this organization is the commercial owner, no external company) or Terceiro (an external origin company is required)
      and production_origin is not null and ((production_origin='own' and org_provider_id is null) or (production_origin='third_party' and org_provider_id is not null))));
create unique index organization_product_routes_v3_key on public.organization_product_routes(organization_id,org_bank_id,coalesce(org_provider_id,'00000000-0000-0000-0000-000000000000'::uuid),org_agreement_id) where org_bank_id is not null;
create index organization_product_routes_org_bank_idx on public.organization_product_routes(organization_id,org_bank_id) where org_bank_id is not null;
create index organization_product_routes_org_provider_idx on public.organization_product_routes(organization_id,org_provider_id) where org_provider_id is not null;
create index organization_product_routes_org_agreement_idx on public.organization_product_routes(organization_id,org_agreement_id) where org_agreement_id is not null;

-- ---------------------------------------------------------------- 3b. payout policies (repasse por grupo, tenant-owned, versioned, immutable)
-- A policy says how much of the commission the company RECEIVED each group gets (e.g. Corretor 65%, Parceiro 80%). One saved policy is reused across hundreds of conditions.
-- Every save creates a NEW immutable version (auditable; changing a policy never rewrites what a condition already used). The base is the gross received commission, or
-- the net base after a configured tax/discount: net = received x (1 - discount/100).  effective group commission = base x group pct / 100.
create table public.payout_policies(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 tech_key text not null default replace(gen_random_uuid()::text,'-',''),
 name text not null check (length(btrim(name)) between 1 and 80),
 is_active boolean not null default true,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (organization_id,id), unique (organization_id,tech_key)
);
create unique index payout_policies_name_key on public.payout_policies(organization_id,lower(btrim(name)));
create table public.payout_policy_versions(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 policy_id uuid not null,
 version integer not null check (version>0),
 base_kind text not null check (base_kind in ('gross','net')),
 discount_pct numeric(9,6) not null default 0 check (discount_pct between 0 and 100),
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 unique (organization_id,id), unique (policy_id,version),
 foreign key (organization_id,policy_id) references public.payout_policies(organization_id,id) on delete restrict,
 check (base_kind='net' or discount_pct=0)
);
create table public.payout_policy_items(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 version_id uuid not null,
 group_id uuid not null,
 pct numeric(9,6) not null check (pct between 0 and 100),
 unique (version_id,group_id),
 foreign key (organization_id,version_id) references public.payout_policy_versions(organization_id,id) on delete restrict,
 foreign key (organization_id,group_id) references public.commission_groups(organization_id,id) on delete restrict
);
create index payout_policy_versions_policy_idx on public.payout_policy_versions(organization_id,policy_id);
create index payout_policy_items_group_idx on public.payout_policy_items(organization_id,group_id);
create trigger payout_policies_00_guard before insert or update on public.payout_policies for each row execute function public.guard_org_catalog_row();

-- Versions and items are written only by save_payout_policy and NEVER changed or removed afterwards (history is not rewritten).
create or replace function public.guard_payout_write() returns trigger language plpgsql set search_path='' as $$
begin
 if tg_op in ('UPDATE','DELETE') and tg_table_name in ('payout_policy_versions','payout_policy_items') then raise exception 'payout_policy_versions_are_immutable'; end if;
 if tg_op='INSERT' and current_user in ('authenticated','anon') and current_setting('corban.payout_rpc',true) is distinct from 'on' then raise exception 'payout_write_requires_governed_rpc'; end if;
 if tg_op='DELETE' then return old; end if;
 return new;
end $$;
create trigger payout_policies_01_token before insert on public.payout_policies for each row execute function public.guard_payout_write();
create trigger payout_policy_versions_00_guard before insert or update or delete on public.payout_policy_versions for each row execute function public.guard_payout_write();
create trigger payout_policy_items_00_guard before insert or update or delete on public.payout_policy_items for each row execute function public.guard_payout_write();
alter table public.payout_policies enable row level security;
alter table public.payout_policy_versions enable row level security;
alter table public.payout_policy_items enable row level security;
revoke all on public.payout_policies,public.payout_policy_versions,public.payout_policy_items from public,anon,authenticated;
grant select,insert,update on public.payout_policies to authenticated;
grant select,insert on public.payout_policy_versions to authenticated;
grant select,insert on public.payout_policy_items to authenticated;
-- financial rules: supervisor and above read, manager and above write (through the RPC)
create policy payout_policies_select on public.payout_policies for select to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager','supervisor']));
create policy payout_policies_insert on public.payout_policies for insert to authenticated with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy payout_policies_update on public.payout_policies for update to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager'])) with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy payout_policy_versions_select on public.payout_policy_versions for select to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager','supervisor']));
create policy payout_policy_versions_insert on public.payout_policy_versions for insert to authenticated with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy payout_policy_items_select on public.payout_policy_items for select to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager','supervisor']));
create policy payout_policy_items_insert on public.payout_policy_items for insert to authenticated with check (public.has_active_organization_role(organization_id,array['admin','manager']));

create or replace function public.save_payout_policy(p_organization uuid,p_name text,p_base_kind text,p_discount numeric,p_items jsonb,p_policy uuid default null)
returns uuid language plpgsql set search_path='' as $$
declare v_pol public.payout_policies%rowtype; v_org uuid; v_ver integer; v_vid uuid; it jsonb; g public.commission_groups%rowtype; v_seen uuid[]:='{}'; v_pct numeric; v_gid uuid; v_disc numeric;
begin
 if auth.uid() is null then raise exception 'not_authorized'; end if;
 if p_policy is not null then
  select * into v_pol from public.payout_policies x where x.id=p_policy for update;
  if not found then raise exception 'policy_not_found'; end if;
  v_org:=v_pol.organization_id;
  if not public.has_active_organization_role(v_org,array['admin','manager']) then raise exception 'not_authorized'; end if;
  if not v_pol.is_active then raise exception 'policy_not_found'; end if;
 else
  v_org:=p_organization;
  if v_org is null or not public.has_active_organization_role(v_org,array['admin','manager']) then raise exception 'not_authorized'; end if;
  if p_name is null or length(btrim(p_name)) not between 1 and 80 then raise exception 'invalid_policy'; end if;
 end if;
 if p_base_kind is null or p_base_kind not in ('gross','net') then raise exception 'invalid_policy'; end if;
 v_disc:=coalesce(p_discount,0);
 if v_disc<0 or v_disc>100 or (p_base_kind='gross' and v_disc<>0) then raise exception 'invalid_policy'; end if;
 if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)>100 then raise exception 'invalid_policy'; end if;
 for it in select * from jsonb_array_elements(p_items) loop
  begin v_gid:=(it->>'group_id')::uuid; v_pct:=(it->>'pct')::numeric; exception when others then raise exception 'invalid_policy'; end;
  if v_gid is null or v_pct is null or v_pct<0 or v_pct>100 then raise exception 'invalid_policy'; end if;
  if v_gid=any(v_seen) then raise exception 'duplicate_group_share'; end if;
  v_seen:=v_seen||v_gid;
  select * into g from public.commission_groups x where x.id=v_gid and x.organization_id=v_org and x.is_active;
  if not found then raise exception 'commission_group_not_found'; end if;
  -- a policy is a percentage of the commission RECEIVED; a production-based group cannot be read that way (no silent mixing)
  if g.calculation_basis<>'percent_of_received_commission' then raise exception 'policy_group_must_use_received_basis'; end if;
 end loop;
 perform set_config('corban.payout_rpc','on',true);
 if p_policy is null then
  begin
   insert into public.payout_policies(organization_id,name,created_by) values(v_org,btrim(p_name),auth.uid()) returning * into v_pol;
  exception when unique_violation then perform set_config('corban.payout_rpc','off',true); raise exception 'policy_already_exists'; end;
 end if;
 select coalesce(max(x.version),0)+1 into v_ver from public.payout_policy_versions x where x.policy_id=v_pol.id;
 insert into public.payout_policy_versions(organization_id,policy_id,version,base_kind,discount_pct,created_by) values(v_org,v_pol.id,v_ver,p_base_kind,v_disc,auth.uid()) returning id into v_vid;
 for it in select * from jsonb_array_elements(p_items) loop
  insert into public.payout_policy_items(organization_id,version_id,group_id,pct) values(v_org,v_vid,(it->>'group_id')::uuid,(it->>'pct')::numeric);
 end loop;
 perform set_config('corban.payout_rpc','off',true);
 return v_vid;
end $$;

-- ---------------------------------------------------------------- 4. commercial conditions
create table public.commercial_conditions(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 product_table_version_id uuid not null,
 contract_type_id uuid not null references public.contract_types(id) on delete restrict,
 term integer not null check (term between 1 and 600),
 coefficient numeric(14,8) check (coefficient is null or coefficient>=0),
 rate numeric(9,6) check (rate is null or rate>=0),
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (organization_id,id),
 unique (product_table_version_id,contract_type_id,term),
 foreign key (organization_id,product_table_version_id) references public.product_table_versions(organization_id,id) on delete restrict,
 check (coefficient is not null or rate is not null)
);
create index commercial_conditions_contract_type_idx on public.commercial_conditions(contract_type_id);
create index commercial_conditions_org_version_idx on public.commercial_conditions(organization_id,product_table_version_id);

create table public.commercial_condition_commissions(
 condition_id uuid primary key,
 organization_id uuid not null references public.organizations(id) on delete restrict,
 received_commission_pct numeric(9,6) not null check (received_commission_pct between 0 and 100),
 -- base actually used for the group payouts: the gross received commission, or the net base after the policy's tax/discount
 net_base_pct numeric(9,6) not null check (net_base_pct between 0 and 100),
 policy_version_id uuid,
 updated_at timestamptz not null default now(),
 foreign key (organization_id,condition_id) references public.commercial_conditions(organization_id,id) on delete restrict,
 foreign key (organization_id,policy_version_id) references public.payout_policy_versions(organization_id,id) on delete restrict
);
create index commercial_condition_commissions_org_idx on public.commercial_condition_commissions(organization_id,condition_id);

create table public.commercial_condition_shares(
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict,
 condition_id uuid not null,
 group_id uuid not null,
 share_pct numeric(9,6) not null check (share_pct between 0 and 100),
 -- what the group really receives as a percentage of the PRODUCTION (received basis: base x share_pct / 100); derived by the RPC, never typed
 effective_pct numeric(9,6) not null check (effective_pct between 0 and 100),
 source text not null default 'manual' check (source in ('manual','policy','override')),
 policy_version_id uuid,
 unique (condition_id,group_id),
 foreign key (organization_id,condition_id) references public.commercial_conditions(organization_id,id) on delete restrict,
 foreign key (organization_id,group_id) references public.commission_groups(organization_id,id) on delete restrict,
 foreign key (organization_id,policy_version_id) references public.payout_policy_versions(organization_id,id) on delete restrict
);
create index commercial_condition_shares_group_idx on public.commercial_condition_shares(organization_id,group_id);

-- Writes only through save_commercial_condition (GUC token) and only while the version is a DRAFT; published versions are frozen with their conditions.
create or replace function public.guard_condition_write() returns trigger language plpgsql set search_path='' as $$
declare v_version uuid; v_status text; v_org uuid;
begin
 if tg_table_name='commercial_conditions' then v_version:=case when tg_op='DELETE' then old.product_table_version_id else new.product_table_version_id end; v_org:=case when tg_op='DELETE' then old.organization_id else new.organization_id end;
 else select c.product_table_version_id,c.organization_id into v_version,v_org from public.commercial_conditions c where c.id=case when tg_op='DELETE' then old.condition_id else new.condition_id end; end if;
 if current_user in ('authenticated','anon') and current_setting('corban.condition_rpc',true) is distinct from 'on' then raise exception 'condition_write_requires_governed_rpc'; end if;
 select v.status into v_status from public.product_table_versions v where v.organization_id=v_org and v.id=v_version;
 if v_status is distinct from 'draft' then raise exception 'published_version_conditions_are_immutable'; end if;
 if tg_op='UPDATE' and (to_jsonb(new)->>'organization_id') is distinct from (to_jsonb(old)->>'organization_id') then raise exception 'catalog_identity_is_immutable'; end if;
 if tg_op='UPDATE' and tg_table_name='commercial_conditions' then
  if (to_jsonb(new)->>'id') is distinct from (to_jsonb(old)->>'id') or (to_jsonb(new)->>'product_table_version_id') is distinct from (to_jsonb(old)->>'product_table_version_id') then raise exception 'catalog_identity_is_immutable'; end if;
 end if;
 if tg_op='DELETE' then return old; end if;
 return new;
end $$;
create trigger commercial_conditions_00_guard before insert or update or delete on public.commercial_conditions for each row execute function public.guard_condition_write();
create trigger commercial_condition_commissions_00_guard before insert or update or delete on public.commercial_condition_commissions for each row execute function public.guard_condition_write();
create trigger commercial_condition_shares_00_guard before insert or update or delete on public.commercial_condition_shares for each row execute function public.guard_condition_write();

alter table public.commercial_conditions enable row level security;
alter table public.commercial_condition_commissions enable row level security;
alter table public.commercial_condition_shares enable row level security;
revoke all on public.commercial_conditions,public.commercial_condition_commissions,public.commercial_condition_shares from public,anon,authenticated;
grant select,insert,update on public.commercial_conditions to authenticated;
grant select,insert,update on public.commercial_condition_commissions to authenticated;
grant select,insert,update,delete on public.commercial_condition_shares to authenticated;
-- pricing (coefficient/rate/term) is what a simulation needs: every member reads it. Commission and shares are supervisor+.
create policy commercial_conditions_select on public.commercial_conditions for select to authenticated using (public.is_active_organization_member(organization_id));
create policy commercial_conditions_insert on public.commercial_conditions for insert to authenticated with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy commercial_conditions_update on public.commercial_conditions for update to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager'])) with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy commercial_condition_commissions_select on public.commercial_condition_commissions for select to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager','supervisor']));
create policy commercial_condition_commissions_insert on public.commercial_condition_commissions for insert to authenticated with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy commercial_condition_commissions_update on public.commercial_condition_commissions for update to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager'])) with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy commercial_condition_shares_select on public.commercial_condition_shares for select to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager','supervisor']));
create policy commercial_condition_shares_insert on public.commercial_condition_shares for insert to authenticated with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy commercial_condition_shares_update on public.commercial_condition_shares for update to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager'])) with check (public.has_active_organization_role(organization_id,array['admin','manager']));
create policy commercial_condition_shares_delete on public.commercial_condition_shares for delete to authenticated using (public.has_active_organization_role(organization_id,array['admin','manager']));

-- ONE call registers the whole condition: pricing + received commission + a share for EVERY commission group informed.
-- p_shares = [{"group_id":"<uuid>","pct":4.5}, ...] (manual, or an override of the policy). p_condition = null creates; otherwise it replaces the condition of THAT draft version.
-- p_policy_version: optional payout policy version; its groups not listed in p_shares are derived from it (source 'policy'); a listed group is an 'override'.
-- Effective commission of a group = pct (production basis) or round(base x pct / 100, 6) (received basis), base = gross received or the policy's net base.
-- A group can never receive more than the company received (per group: groups are alternatives, not a sum).
create or replace function public.save_commercial_condition(p_version uuid,p_contract_type uuid,p_term integer,p_coefficient numeric,p_rate numeric,p_received numeric,p_shares jsonb,p_condition uuid default null,p_policy_version uuid default null)
returns uuid language plpgsql set search_path='' as $$
declare v public.product_table_versions%rowtype; v_id uuid; s jsonb; g public.commission_groups%rowtype; v_seen uuid[]:='{}'; v_pct numeric; v_gid uuid;
 v_pv public.payout_policy_versions%rowtype; v_net numeric; v_rows jsonb:='[]'::jsonb; v_final jsonb:='[]'::jsonb; v_eff numeric; r record;
begin
 if auth.uid() is null then raise exception 'not_authorized'; end if;
 select * into v from public.product_table_versions x where x.id=p_version;
 if not found then raise exception 'version_not_found'; end if;
 if not public.has_active_organization_role(v.organization_id,array['admin','manager']) then raise exception 'not_authorized'; end if;
 if v.status<>'draft' then raise exception 'version_not_draft'; end if;
 if not exists(select 1 from public.contract_types c where c.id=p_contract_type and c.is_active) then raise exception 'contract_type_not_found'; end if;
 if p_term is null or p_term<1 or p_term>600 then raise exception 'invalid_term'; end if;
 if (p_coefficient is null and p_rate is null) or coalesce(p_coefficient,0)<0 or coalesce(p_rate,0)<0 then raise exception 'coefficient_or_rate_required'; end if;
 if p_received is null or p_received<0 or p_received>100 then raise exception 'invalid_received_commission'; end if;
 if p_shares is null or jsonb_typeof(p_shares)<>'array' or jsonb_array_length(p_shares)>100 then raise exception 'invalid_shares'; end if;
 if p_policy_version is not null then
  select pv.* into v_pv from public.payout_policy_versions pv join public.payout_policies pp on pp.id=pv.policy_id and pp.organization_id=pv.organization_id
   where pv.id=p_policy_version and pv.organization_id=v.organization_id and pp.is_active;
  if not found then raise exception 'policy_not_found'; end if;
 end if;
 -- net base after the policy's tax/discount; without a policy (or with a gross policy) the base is the received commission itself
 v_net:=case when p_policy_version is not null and v_pv.base_kind='net' then round(p_received*(100-v_pv.discount_pct)/100,6) else p_received end;
 for s in select * from jsonb_array_elements(p_shares) loop
  begin v_gid:=(s->>'group_id')::uuid; v_pct:=(s->>'pct')::numeric; exception when others then raise exception 'invalid_shares'; end;
  if v_gid is null or v_pct is null or v_pct<0 or v_pct>100 then raise exception 'invalid_shares'; end if;
  if v_gid=any(v_seen) then raise exception 'duplicate_group_share'; end if;
  v_seen:=v_seen||v_gid;
  v_rows:=v_rows||jsonb_build_object('g',v_gid,'pct',v_pct,'src',case when p_policy_version is not null and exists(select 1 from public.payout_policy_items i where i.version_id=p_policy_version and i.group_id=v_gid) then 'override' else 'manual' end);
 end loop;
 if p_policy_version is not null then
  for r in select i.group_id,i.pct from public.payout_policy_items i where i.version_id=p_policy_version and not (i.group_id=any(v_seen)) loop
   v_seen:=v_seen||r.group_id;
   v_rows:=v_rows||jsonb_build_object('g',r.group_id,'pct',r.pct,'src','policy');
  end loop;
 end if;
 for s in select * from jsonb_array_elements(v_rows) loop
  select * into g from public.commission_groups x where x.id=(s->>'g')::uuid and x.organization_id=v.organization_id and x.is_active;
  if not found then raise exception '%',case when s->>'src'='policy' then 'policy_group_inactive' else 'commission_group_not_found' end; end if;
  v_pct:=(s->>'pct')::numeric;
  -- groups are ALTERNATIVE ways the operation can be sold (Corretor OR Parceiro OR Balcao...): the cap is per group, never a sum across groups
  if g.calculation_basis='percent_of_production' then
   if v_pct>p_received then raise exception 'production_shares_exceed_received_commission'; end if;
   v_eff:=v_pct;
  else
   v_eff:=round(v_net*v_pct/100,6);
  end if;
  v_final:=v_final||(s||jsonb_build_object('eff',v_eff));
 end loop;
 perform set_config('corban.condition_rpc','on',true);
 if p_condition is null then
  begin
   insert into public.commercial_conditions(organization_id,product_table_version_id,contract_type_id,term,coefficient,rate,created_by) values(v.organization_id,v.id,p_contract_type,p_term,p_coefficient,p_rate,auth.uid()) returning id into v_id;
  exception when unique_violation then perform set_config('corban.condition_rpc','off',true); raise exception 'condition_already_exists'; end;
 else
  select c.id into v_id from public.commercial_conditions c where c.id=p_condition and c.product_table_version_id=v.id for update;
  if v_id is null then raise exception 'condition_not_found'; end if;
  begin
   update public.commercial_conditions set contract_type_id=p_contract_type,term=p_term,coefficient=p_coefficient,rate=p_rate,updated_at=now() where id=v_id;
  exception when unique_violation then perform set_config('corban.condition_rpc','off',true); raise exception 'condition_already_exists'; end;
 end if;
 insert into public.commercial_condition_commissions(condition_id,organization_id,received_commission_pct,net_base_pct,policy_version_id) values(v_id,v.organization_id,p_received,v_net,p_policy_version)
  on conflict (condition_id) do update set received_commission_pct=excluded.received_commission_pct,net_base_pct=excluded.net_base_pct,policy_version_id=excluded.policy_version_id,updated_at=now();
 delete from public.commercial_condition_shares where condition_id=v_id and not (group_id=any(v_seen));
 for s in select * from jsonb_array_elements(v_final) loop
  insert into public.commercial_condition_shares(organization_id,condition_id,group_id,share_pct,effective_pct,source,policy_version_id)
   values(v.organization_id,v_id,(s->>'g')::uuid,(s->>'pct')::numeric,(s->>'eff')::numeric,s->>'src',case when s->>'src' in ('policy','override') then p_policy_version else null end)
   on conflict (condition_id,group_id) do update set share_pct=excluded.share_pct,effective_pct=excluded.effective_pct,source=excluded.source,policy_version_id=excluded.policy_version_id;
 end loop;
 perform set_config('corban.condition_rpc','off',true);
 return v_id;
end $$;

-- publication: a version may carry its pricing in conditions instead of the legacy scalar rate/coefficient
create or replace function public.publish_product_table_version(p_version_id uuid) returns uuid language plpgsql set search_path='' as $$
declare v public.product_table_versions%rowtype;
begin
 if auth.uid() is null then raise exception 'not_authorized'; end if;
 select * into v from public.product_table_versions x where x.id=p_version_id for update;
 if not found then raise exception 'version_not_found'; end if;
 if not public.has_active_organization_role(v.organization_id,array['admin','manager']) then raise exception 'not_authorized'; end if;
 if v.status<>'draft' then raise exception 'version_not_draft'; end if;
 if v.rate is null and v.coefficient is null and not exists(select 1 from public.commercial_conditions c where c.organization_id=v.organization_id and c.product_table_version_id=v.id) then raise exception 'rate_or_coefficient_required'; end if;
 perform set_config('corban.catalog_rpc','on',true);
 update public.product_table_versions set status='superseded' where organization_id=v.organization_id and product_table_id=v.product_table_id and status='published';
 update public.product_table_versions set status='published',published_at=now(),effective_from=coalesce(effective_from,now()) where id=v.id;
 perform set_config('corban.catalog_rpc','off',true);
 return v.id;
end $$;

-- ---------------------------------------------------------------- 5. governed simulation on a condition (same guarantees as create_simulation)
create or replace function public.create_simulation_for_condition(p_customer_id uuid,p_table_version_id uuid,p_contract_type_id uuid,p_requested_amount numeric,p_term integer)
returns uuid language plpgsql set search_path='' as $$
declare v_customer public.clients%rowtype; v_version public.product_table_versions%rowtype; c public.commercial_conditions%rowtype; v_amount numeric; v_installment numeric; v_id uuid;
begin
 if auth.uid() is null then raise exception 'not_authorized'; end if;
 if p_requested_amount is null or p_requested_amount<=0 or p_requested_amount>999999999 then raise exception 'invalid_amount'; end if;
 if p_term is null or p_term<=0 or p_term>600 then raise exception 'invalid_term'; end if;
 v_amount:=round(p_requested_amount,2);
 select cl.* into v_customer from public.clients cl where cl.id=p_customer_id and cl.deleted_at is null;
 if v_customer.id is null then raise exception 'customer_not_found_or_forbidden'; end if;
 if not public.is_active_organization_member(v_customer.organization_id) then raise exception 'not_authorized'; end if;
 select x.* into v_version from public.product_table_versions x where x.id=p_table_version_id and x.organization_id=v_customer.organization_id and x.status='published';
 if v_version.id is null then raise exception 'published_table_version_not_available'; end if;
 select k.* into c from public.commercial_conditions k where k.organization_id=v_customer.organization_id and k.product_table_version_id=v_version.id and k.contract_type_id=p_contract_type_id and k.term=p_term;
 if c.id is null then raise exception 'condition_not_found'; end if;
 v_installment:=case when c.coefficient is not null and c.coefficient>0 then round(v_amount*c.coefficient,2) else null end;
 perform set_config('corban.simulation_rpc','on',true);
 insert into public.simulations(organization_id,customer_id,product_table_version_id,status,requested_amount,installment_amount,term,rate,coefficient,input_snapshot,result_snapshot,created_by)
 values(v_customer.organization_id,v_customer.id,v_version.id,'calculated',v_amount,v_installment,p_term,c.rate,c.coefficient,
        jsonb_build_object('requested_amount',v_amount,'term',p_term,'contract_type_id',p_contract_type_id,'condition_id',c.id),
        jsonb_build_object('calculation',case when v_installment is null then 'manual_pending' else 'requested_amount_x_coefficient' end),
        auth.uid())
 returning id into v_id;
 perform set_config('corban.simulation_rpc','off',true);
 return v_id;
end $$;

revoke all on function public.guard_org_catalog_row() from public,anon,authenticated;
revoke all on function public.guard_condition_write() from public,anon,authenticated;
revoke all on function public.guard_payout_write() from public,anon,authenticated;
revoke all on function public.save_payout_policy(uuid,text,text,numeric,jsonb,uuid) from public,anon;
grant execute on function public.save_payout_policy(uuid,text,text,numeric,jsonb,uuid) to authenticated;
revoke all on function public.save_commercial_condition(uuid,uuid,integer,numeric,numeric,numeric,jsonb,uuid,uuid) from public,anon;
revoke all on function public.create_simulation_for_condition(uuid,uuid,uuid,numeric,integer) from public,anon;
grant execute on function public.save_commercial_condition(uuid,uuid,integer,numeric,numeric,numeric,jsonb,uuid,uuid) to authenticated;
grant execute on function public.create_simulation_for_condition(uuid,uuid,uuid,numeric,integer) to authenticated;
